Repository WLCG-Lightweight-Sites/wlcg_lightweight_site_wn_pbs, pull requests merged in 2018-10, with the labels that each got.

#13 #12 add basic default data
  default-data.yaml
Labels: enhancement

#14 #12 rename runtime vars in default-data.yaml
  default-data.yaml
Labels: enhancement

#16 #12 add keys for variables
  default-data.yaml
Labels: enhancement

#18 #17 config-schema dummy values added
  config-schema.yaml
Labels: enhancement

#21 #20 update meta-info
  meta-info.yaml
Labels: enhancement

#22 #28 fix syntax of meta info
  meta-info.yaml
Labels: bug

#9 #6 initial changes to the run script
  yaim/run_lwwn.sh
  yaim/wn-config/init.sh
  yaim/wn-config/wn-info.def
Labels: enhancement

#25 Issue 17
  config-schema.yaml
  default-data.yaml
Labels: bug, enhancement
